name: Release To Web Production 
on:
  workflow_dispatch:
    inputs:

      ## Optional field if you want to add description to your apk
      baseUrl:
        description: 'Description'
        required: false
        default: ''

jobs: 
  
  web: 
    name: Release Production Web
    runs-on: ubuntu-20.04
    
    steps:
      - name: Setup Timezone
        run: echo ${{ github.event.repository.updated_at}}
